### PR TITLE
fix: Fix feature count when reserved namespaces present

### LINKED ISSUE #3427: --experimental_full_name_interactions discrepancy with -q
The following should be equivalent commands.

`vw -d test/train-sets/0001.dat --experimental_full_name_interactions ':|:'` and `vw -d test/train-sets/0001.dat -q ::`

However, the total feature number is different. 

Results are:
```
--experimental_full_name_interactions ':|:' -> total feature number = 916116
-q :: -> total feature number = 900634
```

If `--noconstant` is supplied then both results are identical.

### PR DESCRIPTION
**Pull request by jackgerrits**
Fixes #3427

### CODE REVIEW

**Review by bassmang — APPROVED** [review]

File: vowpalwabbit/interactions.h [hunk 1]
```diff
@@ -398,7 +399,18 @@ struct interactions_generator
     for (auto ns_index : indices)
     {
       for (const auto& extent : feature_space[ns_index].namespace_extents)
-      { all_seen_extents.insert({ns_index, extent.hash}); }
+      {
+        // Interactions should not be generated for reserved namespaces such as
+        // constant. These reserved namespaces use their hash as the namespace
+        // character value so we can check if the value is in this range. There
+        // is a chance of collisions here though. 0 is a special case as the
+        // default case is mapped to a hash of 0 even though it is in slot ' ',
```
Comment (olgavrou) [inline vowpalwabbit/interactions.h:407]: super duper nit: maybe don't use `slot` here in the comment because slot is an overloaded term

**Review by olgavrou — APPROVED** [review]
