### PR TITLE
make options a unique_ptr

### LINKED ISSUE #2317: Memory leak in vw_dll_parse_escaped unit test
This unit test ensures that an exception is thrown with this line:
```C++
  BOOST_CHECK_THROW(VW_InitializeA("-d test\\ --nonexistent_option --quiet"), VW::vw_unrecognised_option_exception);
```

However, it seems that this operation is not exception safe causing Valgrind to report leaks in this test.

Once this is fixed we should turn on unit tests in the Valgrind CI.

Related to #2122

### PR DESCRIPTION
**Pull request by olgavrou**
Resolves #2317

### CODE REVIEW

File: vowpalwabbit/global_data.h [hunk 1]
```diff
@@ -382,8 +382,8 @@ struct vw
   vw_ostream trace_message;
 
   // Flag used when VW internally manages lifetime of options object.
-  bool should_delete_options = false;
-  VW::config::options_i* options;
+  bool should_release_options = false;
```
Comment (jackgerrits) [inline vowpalwabbit/global_data.h:385]: This could probably be tracked at creation time of the unique_ptr with the deleter function?

Comment (olgavrou) [reply vowpalwabbit/global_data.h:385]: Not sure what you mean. This is in case we want to delete the options pointer outside of `all` object, so all should just release it.

File: vowpalwabbit/global_data.cc [hunk 2]
```diff
@@ -366,7 +366,7 @@ vw::~vw()
   }
 
   // Check if options object lifetime is managed internally.
-  if (should_delete_options) delete options;
+  if (should_release_options) options.release();
```
Comment (jackgerrits) [inline vowpalwabbit/global_data.cc:369]: This will leak I think? Release removes the ptr from being managed

File: vowpalwabbit/parse_args.cc [hunk 3]
```diff
@@ -1672,9 +1674,19 @@ void free_args(int argc, char* argv[])
 }
 
 vw* initialize(
-    options_i& options, io_buf* model, bool skipModelLoad, trace_message_t trace_listener, void* trace_context)
+    config::options_i& options, io_buf* model, bool skipModelLoad, trace_message_t trace_listener, void* trace_context)
 {
-  vw& all = parse_args(options, trace_listener, trace_context);
+  std::unique_ptr<options_i> opts;
```
Comment (jackgerrits) [inline vowpalwabbit/parse_args.cc:1679]: Since the options object is managed externally we can add a custom deleter which is a noop for the unique_ptr, rather than needing to manage the external state of `should_release_options`

Comment (olgavrou) [reply vowpalwabbit/parse_args.cc:1679]: ah good point

File: vowpalwabbit/global_data.h (hunk 1 above)
Comment (jackgerrits) [reply vowpalwabbit/global_data.h:385]: Added a comment at the spot where we'd need to do it.

Instead of using the `should_release_options` state, we can just make the deleter of the unique_ptr a noop in the cases where we would have called release. This also mitigates the case where an exception would have caused the object we're meant to release to be deleted.

**Review by jackgerrits — APPROVED** [review]
