### PR TITLE
Fix Slates crash

### LINKED ISSUE #2472: Slates DSJSON format without an "_outcomes" field causes a crash
If you do not populate the "_outcomes" field (or it is named something else), then it causes a crash. This is kind of low impact because pretty much every DSJSON log that is passed will contain the outcomes field, but it is still an issue.

Input:
```
{"_label_cost":1,"c":{"shared_feature":1.0,"_multi":[{"_slot_id":0,"feature":1.0},{"_slot_id":0,"feature":1.0},{"_slot_id":0,"feature":1.0},{"_slot_id":1,"feature":1.0},{"_slot_id":1,"feature":1.0}],"_slots":[{"feature":1.0},{"feature":1.0}]},"_outcomes__":[{"_a":[1,0,2],"_p":[0.8,0.1,0.1]},{"_a":[0,1],"_p":[0.6,0.4]}]}
{"_label_cost":1,"c":{"shared_feature":1.0,"_multi":[{"_slot_id":0,"feature":1.0},{"_slot_id":0,"feature":1.0},{"_slot_id":0,"feature":1.0},{"_slot_id":1,"feature":1.0},{"_slot_id":1,"feature":1.0}],"_slots":[{"feature":1.0},{"feature":1.0}]},"_outcomes__":[{"_a":[1,0,2],"_p":[0.8,0.1,0.1]},{"_a":[0,1],"_p":[0.6,0.4]}]}
```

Command line: `-d ../../../file_with_above_contents_above.dsjson  --dsjson --slates`

Output:
```
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = ../../../slates.dsjson
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
fish: “vowpalwabbit/vw -d ../../../sla…” terminated by signal SIGSEGV (Address boundary error)
```

It seems to be caused by the fact that the slates dsjson parser does not record the logged actions when they aren't passed, but this in turn causes a "reread" loop. The resulting examples list becomes huge and causes crashes further on.

### PR DESCRIPTION
**Pull request by jackgerrits**
Resolves #2472

### CODE REVIEW

File: vowpalwabbit/parse_example_json.h [hunk 1]
```diff
@@ -1594,8 +1594,8 @@ bool parse_line_json(vw* all, char* line, size_t num_chars, v_array<example*>& e
     // let's ask to continue reading data until we find a line with actions provided
     if (interaction.actions.size() == 0)
     {
-      // VW::return_multiple_example(*all, examples);
-      // examples.push_back(&VW::get_unused_example(all));
+      VW::return_multiple_example(*all, examples);
```
Comment (lalo) [inline vowpalwabbit/parse_example_json.h:1597]: why was this fix as easy as uncommenting this? or was it commented by mistake to begin with

Comment (jackgerrits) [reply vowpalwabbit/parse_example_json.h:1597]: I talked to Jacob about it, he believes it's okay to uncomment here. This is the original PR: https://github.com/VowpalWabbit/vowpal_wabbit/pull/1878

**Comment by jackgerrits** [comment]
Seems like the C# unit tests can't handle dsjson so I had to skip it
