### PR TITLE
fix: remove std::iterator from slimvw to resolve build issues

### LINKED ISSUE #3238: VWSlim does not build with v142 or v143 build tools
#### Describe the bug
VWSlim builds with v141 build tools but not v142 or v143.

#### Expected behavior
VWSlim builds with v141, v142 and v143 build tools.

#### Observed Behavior
VWSlim does not build with v142 or v143 build tools.

The error is to with a custom iterator I think.
```
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30423\include\algorithm(7248,1): error C2678: binary '*': no operator found which takes a left-hand operand of type 'const _BidIt' (or there is no acceptable conversion)
1>        with
1>        [
1>            _BidIt=iter
1>        ]
1>C:\w\win\vowpal_wabbit\vowpalwabbit\slim\include\vw_slim_predict.h(103,7): message : could be 'vw_slim::internal::location_reference<FirstIt,SecondIt> vw_slim::internal::collection_pair_iterator<FirstIt,SecondIt>::operator *(void)'
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30423\include\algorithm(7248,1): message : while trying to match the argument list '(const _BidIt)'
1>        with
1>        [
1>            _BidIt=iter
1>        ]
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30423\include\algorithm(7372): message : see reference to function template instantiation '_BidIt std::_Insertion_sort_unchecked<_RanIt,_Pr>(const _BidIt,const _BidIt,_Pr)' being compiled
1>        with
1>        [
1>            _BidIt=iter,
1>            _RanIt=iter,
1>            _Pr=PairIteratorTestSuite_simple_test_Test::TestBody::<lambda_b8bdbdd5c8ef4ee5b1d8d2dab8212907>
1>        ]
```
#### Environment
What version of VW did you use? Windows 10
What OS or language did you use? VS 2019 with v143, v142 and v141 build tools installed.

### PR DESCRIPTION
**Pull request by jackgerrits**
Resolves #3238

### CODE REVIEW

**Review by bassmang — APPROVED** [review]

File: vowpalwabbit/slim/include/vw_slim_predict.h [hunk 1]
```diff
@@ -589,16 +438,36 @@ class vw_predict
...
+      ++ranking_it;
+    }
+
+    std::sort(zipped_values.begin(), zipped_values.end(),
+        [](const zipped_tuple_t& l, const zipped_tuple_t& r) { return std::get<1>(l) < std::get<1>(r); });
+
+    for (const auto& zipped_value : zipped_values)
+    {
+      *pdf_first = std::get<0>(zipped_value);
+      *ranking_begin = std::get<2>(zipped_value);
```
Comment (olgavrou) [inline vowpalwabbit/slim/include/vw_slim_predict.h:467]: do we need to also update the scores iterator here? or is it only used for sorting?

Comment (jackgerrits) [reply vowpalwabbit/slim/include/vw_slim_predict.h:467]: Only used for sorting. Based on the previous code the collection was not modified

**Review by olgavrou — APPROVED** [review]
